### ISSUE TITLE
clean up for for version 0.02.00

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#417]
This issue tracks several cleaning up which is incompatible with old versions:

- [x] remove wpantund mode support (#403)
- [x] remove otbr-commissioner(including third_party/libcoap) (#420)
- [x] switch to cmake for otbr-agent and otbr-web (#405)
- [x] add ot-ctl (#422)
- [ ] update document on openthread.io and merge into master branch

**Comment by gabekassel** [comment]
@bukepo I'm seeing issues building the 0.02.00 branch in Yocto with cmake. I'm able to build openthread repo in Yocto with cmake without issue. Curious if you're interested in feedback or willing to help debug. If this branch is still too much in development, I'm happy to wait. 

Overall, I was hoping to base on the "new" stuff rather than wpantund. Also cmake seems to player nicer with Yocto than automake.

**Comment by bukepo** [comment]
@gabekassel I'm doing some final cleaning up for this branch. Hopefully this can be done within this week.

**Comment by gabekassel** [comment]
Ok. I'll hold for now then start asking questions. Thanks for getting this completed!
